// tests/demo-record.js
// Marketing demo: AI agent plays user, genuine voice-to-voice conversation with Sofia.
//
// Usage:
//   node tests/demo-record.js              # full 7-minute run
//   DEMO_MAX_TURNS=3 node tests/demo-record.js   # short 3-turn test
//
// Prerequisites:
//   - VB-CABLE installed and CABLE Output set as the DEFAULT Windows Recording device
//     (right-click speaker icon → Sounds → Recording → set "CABLE Output" as Default)
//   - OBS Studio open, WebSocket server enabled on port 4455 (Tools → obs-websocket Settings)
//   - OBS scene capturing the browser window
//   - OPENAI_API_KEY and GROQ_API_KEY in .env
//
// Real STT path (no mock):
//   1. AI user reply generated by Groq
//   2. Text → MP3 via OpenAI TTS (tts-1-hd / echo voice — "Alex")
//   3. MP3 → WAV, played to "CABLE Input" via WinMM (tests/helpers/play-to-cable.ps1)
//   4. VB-CABLE routes CABLE Input → CABLE Output (virtual mic)
//   5. Browser's real webkitSpeechRecognition hears it and fires onresult
//   6. App processes transcript → Sofia responds via Fish Audio TTS

'use strict';
const { chromium }    = require('playwright');
const fs              = require('fs');
const path            = require('path');
const crypto          = require('crypto');
const { execSync, spawnSync } = require('child_process');
const os                      = require('os');

// Load .env
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

// ── Config ─────────────────────────────────────────────────────────────────────
const LIVE_URL        = 'https://www.eklipses.com';
const GROQ_KEY        = process.env.GROQ_API_KEY;
const GROQ_MODEL      = 'qwen/qwen3.8-27b';
const OPENAI_KEY      = process.env.OPENAI_API_KEY;
// User voice: OpenAI tts-1-hd "echo". Fish Audio voices failed Chrome STT; echo is proven.
// Ryan's Fish Audio voice (coach) is reserved for post-session coaching only.
const OBS_WS      = 'ws://localhost:4455';
const OBS_PASS    = process.env.OBS_WS_PASSWORD || '';
const SESSION_MS  = 7 * 60 * 1000;  // 7 minutes
const MAX_TURNS   = process.env.DEMO_MAX_TURNS ? parseInt(process.env.DEMO_MAX_TURNS, 10) : Infinity;
const OUT_DIR     = path.join(__dirname, 'output');
const STAMP       = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
const TRANSCRIPT  = path.join(OUT_DIR, `demo-transcript-${STAMP}.txt`);
const PLAY_SCRIPT = path.join(__dirname, 'helpers', 'play-to-cable.ps1');
const SCRATCH_DIR = os.tmpdir();

if (!GROQ_KEY)    { console.error('[DEMO] GROQ_API_KEY not set in .env'); process.exit(1); }
if (!OPENAI_KEY)  { console.error('[DEMO] OPENAI_API_KEY not set — real STT requires TTS audio'); process.exit(1); }

// ── OBS WebSocket ───────────────────────────────────────────────────────────────

let obsWs = null;
let obsReqCounter = 0;
const obsCallbacks = new Map();

function obsConnect() {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(OBS_WS);
    obsWs = ws;
    let ready = false;

    ws.onmessage = ev => {
      let msg;
      try { msg = JSON.parse(ev.data); } catch { return; }

      // op:0 = Hello
      if (msg.op === 0) {
        const identify = { op: 1, d: { rpcVersion: 1 } };
        if (OBS_PASS && msg.d.authentication) {
          const { challenge, salt } = msg.d.authentication;
          const secret = crypto.createHash('sha256')
            .update(OBS_PASS + salt).digest('base64');
          identify.d.authentication = crypto.createHash('sha256')
            .update(secret + challenge).digest('base64');
        }
        ws.send(JSON.stringify(identify));
        return;
      }

      // op:2 = Identified
      if (msg.op === 2) {
        ready = true;
        console.log('[OBS] Connected and identified');
        resolve(ws);
        return;
      }

      // op:7 = RequestResponse
      if (msg.op === 7) {
        const cb = obsCallbacks.get(msg.d.requestId);
        if (cb) { obsCallbacks.delete(msg.d.requestId); cb(msg.d); }
        return;
      }
    };

    ws.onerror = err => { if (!ready) reject(new Error('OBS WS error: ' + err.message)); };
    ws.onclose = () => { if (!ready) reject(new Error('OBS WS closed before Identified')); };
  });
}

function obsReq(type, data = {}) {
  return new Promise((resolve, reject) => {
    const id = 'r' + (++obsReqCounter);
    const timer = setTimeout(() => {
      obsCallbacks.delete(id);
      reject(new Error('OBS request timeout: ' + type));
    }, 15000);
    obsCallbacks.set(id, d => { clearTimeout(timer); resolve(d); });
    obsWs.send(JSON.stringify({ op: 6, d: { requestType: type, requestId: id, requestData: data } }));
  });
}

async function obsStartRecord() {
  // Stop any recording already in progress (e.g. left over from a crashed run)
  try {
    const check = await obsReq('GetRecordStatus');
    if (check.responseData?.outputActive) {
      console.log('[OBS] Stopping previous recording...');
      await obsReq('StopRecord');
      await new Promise(r => setTimeout(r, 1500));
    }
  } catch { /* not recording — that's fine */ }

  const d = await obsReq('StartRecord');
  if (!d.requestStatus.result) throw new Error('OBS StartRecord failed: ' + JSON.stringify(d.requestStatus));
  console.log('[OBS] Recording started');
}

async function obsStopRecord() {
  const d = await obsReq('StopRecord');
  const out = d.responseData?.outputPath || '(unknown — check OBS output folder)';
  console.log('[OBS] Recording stopped →', out);
  return out;
}

// ── AI user agent ───────────────────────────────────────────────────────────────
// Calls Groq to generate a natural, reactive reply from the "user" perspective.
// Sofia's full character prompt lives in api/character-stream.js — the AI user
// only needs to know the high-level context.

const aiUserHistory = [];  // [{role,content}] — what the AI user remembers saying

async function aiUserReply(sofiaText, turnNumber) {
  const isOpener  = turnNumber === 1;
  const isEarly   = turnNumber <= 3;
  const isMid     = turnNumber > 3 && turnNumber <= 9;
  const isLate    = turnNumber > 9;

  let phase = '';
  if (isOpener) {
    phase = `This is the OPENING LINE. You're approaching Sofia for the first time at a quiet beach. ` +
      `She's sitting writing in her notebook. You've just walked up. ` +
      `Give a brief, genuine opener — not a pickup line. Something you'd actually say.`;
  } else if (isEarly) {
    phase = `Early in the conversation — 2nd or 3rd exchange. Build on what she said. ` +
      `Still a bit uncertain but genuinely interested.`;
  } else if (isMid) {
    phase = `Mid conversation — you've had a few good exchanges. Be more confident now. ` +
      `Show real interest in her article (shoreline erosion, 20 years of data). ` +
      `Around turn 7-9, if things are going well, try a soft invite: coffee, a walk, etc.`;
  } else {
    phase = `Late conversation. You've built real rapport. ` +
      `Be direct. If you haven't already, try asking for her number or to get coffee. ` +
      `Don't drag it out — make the move.`;
  }

  const systemPrompt =
    `/no_think You are playing the role of a man (mid-20s) who has just approached a woman at the beach.
Sofia is 26, writes for an independent magazine about coastal ecology, working on an article about how a local shoreline has lost 8 metres of sand in 20 years.

${phase}

Sofia's character: guarded but genuinely curious about people. Dry wit. She makes you earn her attention. She does NOT reward generic questions — only genuine, specific ones.

STRICT RULES:
- Write 1-2 sentences. HARD LIMIT: each sentence must be 15 words or fewer. Count before you write.
- Spoken dialogue only. No stage directions.
- React SPECIFICALLY to what Sofia just said. Be concrete, not vague.
- Do NOT ask two questions back to back.
- Do NOT be smooth or rehearsed — natural imperfection is fine.
- Do NOT use exclamation marks. Speak like a real person, not a chatbot.
- Do NOT start with "I" if you can help it — vary your sentence starters.
- Never say "That's interesting" or "That's fascinating" or generic filler.
- You are the MAN. Sofia is the WOMAN you are speaking to. NEVER introduce yourself as Sofia or use her name as your own.

Return only the spoken line. Nothing else.`;

  // Role mapping: user = Sofia's lines (she speaks TO you), assistant = the man's replies.
  // This matches how Groq sees itself (as assistant) so it stays in the man's perspective,
  // not Sofia's — the previous inverted mapping caused the model to occasionally claim her name.
  const messages = [
    { role: 'system', content: systemPrompt },
    ...aiUserHistory.slice(-12),
  ];

  if (!isOpener && sofiaText) {
    messages.push({ role: 'user', content: sofiaText });
  } else {
    messages.push({ role: 'user', content: isOpener
      ? 'Make your opening move. One or two short sentences, genuine.'
      : 'Continue the conversation. One or two short sentences.' });
  }

  let res, lastErrText;
  for (let attempt = 0; attempt < 2; attempt++) {
    res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${GROQ_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        messages,
        max_tokens: 80,
        temperature: 0.88,
      }),
    });

    if (res.status !== 429) break;

    // Rate limited — parse retry-after from error body and wait
    lastErrText = await res.text();
    const retryMatch = lastErrText.match(/try again in ([\d.]+)s/);
    const waitMs = retryMatch ? Math.ceil(parseFloat(retryMatch[1]) * 1000) + 500 : 15000;
    console.log(`[DEMO] Rate limited — waiting ${(waitMs / 1000).toFixed(1)}s before retry...`);
    await new Promise(r => setTimeout(r, waitMs));
  }

  if (!res.ok) {
    // Body already consumed if we hit 429 on final attempt — reuse stashed text
    const err = lastErrText ?? await res.text();
    throw new Error(`Groq API ${res.status}: ${err}`);
  }

  const data = await res.json();
  const reply = (data.choices[0].message.content || '').trim()
    .replace(/^["']|["']$/g, '');  // strip surrounding quotes if model adds them

  // Remember it: user = Sofia (speaks to us), assistant = the man (our reply)
  if (sofiaText) aiUserHistory.push({ role: 'user', content: sofiaText });
  aiUserHistory.push({ role: 'assistant', content: reply });

  return reply;
}

// ── OpenAI TTS for AI user lines (echo / "Alex" voice) ────────────────────────
async function openAITTS(text) {
  const res = await fetch('https://api.openai.com/v1/audio/speech', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${OPENAI_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ model: 'tts-1-hd', voice: 'echo', input: text, response_format: 'mp3' }),
  });
  if (!res.ok) throw new Error(`OpenAI TTS ${res.status}: ${await res.text()}`);
  return Buffer.from(await res.arrayBuffer());
}

// Split reply into sentences for per-sentence TTS — echo sounds natural on short chunks,
// robotic on long run-ons. Groq prompt caps at 15 words/sentence; this is a safety net.
function splitSentences(text) {
  return text
    .split(/(?<=[.!?])\s+/)
    .map(s => s.trim())
    .filter(s => s.length > 0);
}

async function openAITTSSentences(text) {
  return Promise.all(splitSentences(text).map(s => openAITTS(s)));
}

// ── Play audio into VB-CABLE Input AND default speakers ───────────────────────
// Two parallel streams for the same WAV:
//   1. WinMM WaveOut → CABLE Input → VB-CABLE → CABLE Output → Chrome STT
//   2. ffplay → default speakers → audible in room + OBS desktop-audio track
// Returns a Promise that resolves only when BOTH WinMM AND ffplay have finished,
// so multi-sentence callers can await each sentence before starting the next.
async function playToCableInput(audioBuffer) {
  const id      = Date.now();
  const mp3File = path.join(SCRATCH_DIR, `ek-tts-${id}.mp3`);
  const wavFile = path.join(SCRATCH_DIR, `ek-tts-${id}.wav`);

  fs.writeFileSync(mp3File, audioBuffer);
  // Convert MP3 → PCM WAV that WinMM can play directly
  execSync(
    `ffmpeg -y -i "${mp3File}" -ar 44100 -ac 1 -acodec pcm_s16le "${wavFile}"`,
    { stdio: 'pipe', timeout: 30000 },
  );
  try { fs.unlinkSync(mp3File); } catch {}

  // Stream 2: ffplay to default speakers (async — runs concurrently with WinMM)
  const { spawn } = require('child_process');
  const ffp = spawn('ffplay', ['-nodisp', '-autoexit', '-i', wavFile],
    { stdio: 'pipe', windowsHide: true });
  // Promise settles when ffplay exits (execSync below blocks the event loop, so this
  // resolves in the next tick after execSync returns if ffplay has already finished)
  const ffplayDone = new Promise(resolve => {
    ffp.on('exit', resolve);
    ffp.on('error', resolve);
  });

  // Stream 1: WinMM → CABLE Input (blocks event loop until WHDR_DONE)
  try {
    execSync(
      `powershell.exe -NonInteractive -File "${PLAY_SCRIPT}" "${wavFile}" "CABLE Input"`,
      { stdio: 'pipe', timeout: 60000 },
    );
  } catch (err) {
    ffp.kill();
    try { fs.unlinkSync(wavFile); } catch {}
    throw err;
  }

  // Wait for ffplay to finish before returning — prevents sentences overlapping
  await ffplayDone;
  try { fs.unlinkSync(wavFile); } catch {}
}

// ── Pre-flight: verify VB-CABLE Output is present as a recording device ────────
function checkVBCable() {
  // spawnSync always captures stderr regardless of exit code (ffmpeg exits 0 here)
  const r = spawnSync('ffmpeg', ['-list_devices', 'true', '-f', 'dshow', '-i', 'dummy'],
    { encoding: 'utf8', stdio: 'pipe' });
  const output = (r.stdout || '') + (r.stderr || '');
  if (!output.includes('CABLE Output')) {
    console.error('[DEMO] ABORT: "CABLE Output (VB-Audio Virtual Cable)" not found as a recording device.');
    console.error('[DEMO] Install VB-CABLE from vb-audio.com, reboot, then re-run.');
    console.error('[DEMO] ffmpeg saw:', output.split('\n').filter(l => l.includes('audio')).join(' | '));
    process.exit(1);
  }
  console.log('[DEMO] VB-CABLE Output confirmed present.');
  console.log('[DEMO] IMPORTANT: Ensure "CABLE Output" is the DEFAULT recording device');
  console.log('[DEMO]   (webkitSpeechRecognition always uses the OS default — set it in Sound Settings → Recording)');
}

// ── Main ────────────────────────────────────────────────────────────────────────

async function main() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  // ── Step 0: VB-CABLE pre-flight ─────────────────────────────────────────────
  checkVBCable();

  // ── Step 1: Connect to OBS (skip if DEMO_NO_OBS=1) ────────────────────────
  const noObs = process.env.DEMO_NO_OBS === '1';
  if (noObs) {
    console.log('[DEMO] DEMO_NO_OBS=1 — skipping OBS (conversation + screenshots only, no video recording)');
  } else {
    console.log('[DEMO] Connecting to OBS WebSocket at', OBS_WS, '...');
    console.log('[DEMO] (Make sure OBS is open with Tools → obs-websocket Settings → Enable on port 4455)');
    try {
      await obsConnect();
    } catch (err) {
      console.error('[DEMO] OBS connection failed:', err.message);
      console.error('[DEMO] Open OBS Studio or set DEMO_NO_OBS=1 to skip OBS entirely.');
      process.exit(1);
    }
  }

  // ── Step 2: Launch browser (visible so OBS can capture it) ──────────────────
  console.log('[DEMO] Launching browser...');
  const browser = await chromium.launch({
    headless: false,
    args: [
      '--kiosk',                          // fullscreen, no address bar
      '--no-sandbox',
      '--use-fake-ui-for-media-stream',   // auto-grant mic without dialog; uses real default device
      '--autoplay-policy=no-user-gesture-required',
    ],
  });
  // Grant microphone permission so webkitSpeechRecognition can use CABLE Output
  const ctx  = await browser.newContext({ viewport: null, permissions: ['microphone'] });
  const page = await ctx.newPage();

  // Capture console logs for debugging
  page.on('console', msg => {
    if (msg.type() === 'error') console.log('[PAGE ERR]', msg.text().slice(0, 120));
  });

  // No addInitScript — real webkitSpeechRecognition is used (no mock).

  // ── Step 3: Navigate to app + set localStorage ──────────────────────────────
  console.log('[DEMO] Navigating to', LIVE_URL, '...');
  await page.goto(LIVE_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });

  // Set before reload so the app reads them on init
  await page.evaluate(() => {
    localStorage.setItem('ek-dev-key', 'ek_dev_2026');          // bypass paywall
    localStorage.setItem('eklipses_input_mode', 'voice');        // voice mode — mock STT intercepts
    localStorage.setItem('ek-onboarding-v1', '1');               // skip onboarding overlay
    localStorage.setItem('ek-practice-banner-dismissed', '1');   // skip lesson banner
  });

  await page.reload({ waitUntil: 'networkidle', timeout: 30000 });

  // ── Step 4: Dismiss the hero-v6 intro overlay (blocks tab clicks if present) ─
  const heroPresent = await page.$('#ek-hero-v6');
  if (heroPresent) {
    console.log('[DEMO] Dismissing hero overlay...');
    await page.waitForSelector('#ek-h6-start', { timeout: 10000 });
    await page.click('#ek-h6-start');
    await page.waitForSelector('#ek-hero-v6', { state: 'detached', timeout: 20000 });
  }

  // ── Step 5: Switch to Practice tab + launch beach scenario via JS ────────────
  // We call switchTab and playScenario directly — no card click needed, and it
  // avoids a timing race waiting for card visibility after Kokoro loads.
  console.log('[DEMO] Switching to Practice tab and launching beach/Sofia scenario...');
  await page.evaluate(() => {
    // switchTab is defined inside an IIFE in lesson-player.js; expose it by
    // clicking the tab button programmatically so the registered onclick fires.
    const btn = document.getElementById('ek-tab-practice');
    if (btn) btn.click();
  });
  await new Promise(r => setTimeout(r, 500));

  // ── Step 6: Preflight screenshot (confirms Practice UI, not lesson list) ────
  const preflightPng = path.join(OUT_DIR, `demo-preflight-${STAMP}.png`);
  await page.screenshot({ path: preflightPng });
  console.log('[DEMO] Preflight screenshot:', preflightPng);

  // ── Step 7: Launch Sofia/beach scenario via direct JS call ──────────────────
  // playScenario is a global in player.js. beach is a coldOpen scenario so it
  // goes straight to freeConversation — Sofia's video appears, timer starts.
  console.log('[DEMO] Calling playScenario("beach")...');
  // Do NOT await the returned promise — playScenario runs freeConversation for 7
  // minutes and would block page.evaluate for the entire session. Fire and forget.
  await page.evaluate(() => { playScenario('beach', false); });

  // Short pause for transition animation
  await new Promise(r => setTimeout(r, 2500));

  // ── Step 7: Wait for manual OBS window-capture alignment (skipped in DEMO_NO_OBS) ─
  if (!noObs) {
    if (process.env.DEMO_SKIP_PAUSE !== '1') {
      await new Promise(resolve => {
        const rl = require('readline').createInterface({ input: process.stdin, output: process.stdout });
        rl.question('\n[DEMO] Point OBS\'s Window Capture to the new browser window now, then press Enter to start recording: ', () => {
          rl.close();
          resolve();
        });
      });
    } else {
      console.log('\n[DEMO] DEMO_SKIP_PAUSE=1 — skipping OBS alignment pause, starting recording now.');
    }
    // ── Step 8: Start OBS recording ───────────────────────────────────────────
    await obsStartRecord();
  }

  // ── Step 9: Mid-scenario confirmation screenshot ────────────────────────────
  // (Confirms we're in the live scenario, not the static lesson list)
  await new Promise(r => setTimeout(r, 3000));
  const confirmPng = path.join(OUT_DIR, `demo-scenario-confirm-${STAMP}.png`);
  await page.screenshot({ path: confirmPng });
  console.log('[DEMO] Scenario confirmation screenshot:', confirmPng);

  // Verify the scenario UI is actually showing (not lesson list)
  const scenarioVisible = await page.evaluate(() => {
    const name = document.getElementById('speakerName');
    const frame = document.getElementById('stageFrame');
    return !!(name && frame && frame.offsetParent !== null);
  });
  if (!scenarioVisible) {
    console.error('[DEMO] ABORT: Scenario UI not visible — check screenshot for what actually loaded');
    if (!noObs) await obsStopRecord();
    await browser.close();
    process.exit(1);
  }
  console.log('[DEMO] Scenario UI confirmed visible. Sofia should be on screen.');

  // ── Step 10: Handle style-picker modal if it appeared ──────────────────────
  // A "How do you want to play this?" modal (Curious/Playful/Direct) may appear
  // after playScenario. Click through it before waiting for the conversation UI.
  try {
    await page.waitForSelector('text=How do you want to play this?', { timeout: 8000, state: 'visible' });
    console.log('[DEMO] Style picker appeared — selecting "Playful"...');
    await page.click('text=Playful');
    await new Promise(r => setTimeout(r, 1000));
  } catch {
    // No style picker — scenario started directly, that's fine
  }

  // ── Step 11: Wait for voice listen-pill (Sofia done with opening line, our turn) ──
  console.log('[DEMO] Waiting for voice input to become active (Sofia ready for first user message)...');
  await page.waitForFunction(
    () => {
      const p = document.getElementById('listenPill');
      return p && p.style.display === 'block';
    },
    null,
    { timeout: 90000 }, // 90s: Sofia generates + speaks her opening line first
  );
  console.log('[DEMO] Voice input is live — conversation starting!\n');

  // ── Step 12: AI-vs-AI voice conversation loop ────────────────────────────────
  const sessionStart = Date.now();
  let turn = 0;
  const transcriptLines = [
    '=== Eklipses Marketing Demo — AI vs Sofia (voice-to-voice) ===',
    `Date: ${new Date().toISOString()}`,
    `URL: ${LIVE_URL}`,
    `AI user TTS: OpenAI tts-1-hd / echo (sentence-split)`,
    `Sofia TTS: Fish Audio (production voices)`,
    '',
  ];

  while (Date.now() - sessionStart < SESSION_MS && turn < MAX_TURNS) {
    turn++;
    const elapsedMin = ((Date.now() - sessionStart) / 60000).toFixed(1);

    // Read Sofia's latest response from conversationHistory
    const history = await page.evaluate(() => {
      try { return Array.isArray(conversationHistory) ? conversationHistory : []; }
      catch { return []; }
    });

    const lastSofia = [...history].reverse().find(h => h.role === 'assistant');
    const sofiaText = lastSofia?.content || '';

    if (sofiaText) {
      console.log(`[T${turn} @${elapsedMin}m] SOFIA: ${sofiaText.slice(0, 100)}${sofiaText.length > 100 ? '...' : ''}`);
      transcriptLines.push(`[T${turn}] SOFIA: ${sofiaText}`);
    }

    // Generate AI user reply text
    let userReply;
    try {
      userReply = await aiUserReply(sofiaText, turn);
    } catch (err) {
      console.error('[DEMO] Groq error:', err.message);
      userReply = 'That\'s really interesting.';
    }

    // Fetch TTS per sentence — echo sounds natural on ≤15-word chunks, robotic on long runs.
    let sentenceBufs = null;
    try {
      sentenceBufs = await openAITTSSentences(userReply);
      const totalBytes = sentenceBufs.reduce((s, b) => s + b.length, 0);
      console.log(`[T${turn} @${elapsedMin}m] USER (TTS ${totalBytes}b, ${sentenceBufs.length} sent): ${userReply}`);
    } catch (err) {
      console.error('[DEMO] OpenAI TTS error:', err.message, '— cannot continue without audio');
      break;
    }

    transcriptLines.push(`[T${turn}] USER: ${userReply}`);
    transcriptLines.push('');

    // Natural hesitation pause before speaking
    const thinkMs = 600 + Math.random() * 800;
    await new Promise(r => setTimeout(r, thinkMs));

    // Play each sentence sequentially. 150ms gap stays below Chrome STT silence threshold
    // (~500-1000ms), so onresult fires only after the full turn, not mid-sentence.
    try {
      for (let si = 0; si < sentenceBufs.length; si++) {
        await playToCableInput(sentenceBufs[si]);
        if (si < sentenceBufs.length - 1) {
          await new Promise(r => setTimeout(r, 150));
        }
      }
    } catch (err) {
      console.error('[DEMO] CABLE Input playback error:', err.message);
      break;
    }

    // Wait for STT silence detection to fire (Chrome fires ~500-1000ms after audio ends)
    await new Promise(r => setTimeout(r, 1800));

    // Wait for listen-pill to disappear (Sofia is generating + speaking)
    await page.waitForFunction(
      () => {
        const p = document.getElementById('listenPill');
        return !p || p.style.display !== 'block';
      },
      null,
      { timeout: 15000 },
    ).catch(() => {});

    // Wait for listen-pill to reappear (Sofia done, our turn again)
    try {
      await page.waitForFunction(
        () => {
          const p = document.getElementById('listenPill');
          return p && p.style.display === 'block';
        },
        null,
        { timeout: 70000 }, // up to 70s for multi-sentence TTS playback
      );
    } catch {
      console.log('[DEMO] Timeout waiting for Sofia — may have hit session end or error');
      break;
    }
  }

  // ── Step 12: Cooldown / stop OBS ────────────────────────────────────────────
  const cooldownMs = noObs ? 5000 : 30000;
  console.log(`\n[DEMO] Conversation loop done. Waiting ${cooldownMs / 1000}s cooldown...`);
  await new Promise(r => setTimeout(r, cooldownMs));

  let recordingPath = '(no OBS recording)';
  if (!noObs) {
    console.log('[DEMO] Stopping OBS recording...');
    recordingPath = await obsStopRecord();
  }

  // ── Step 14: Save transcript ─────────────────────────────────────────────────
  transcriptLines.push('=== SESSION END ===');
  transcriptLines.push(`Duration: ${((Date.now() - sessionStart) / 60000).toFixed(1)} minutes`);
  transcriptLines.push(`Turns: ${turn}`);
  fs.writeFileSync(TRANSCRIPT, transcriptLines.join('\n'));
  console.log('[DEMO] Transcript saved:', TRANSCRIPT);

  // Final screenshot
  const finalPng = path.join(OUT_DIR, `demo-final-${STAMP}.png`);
  await page.screenshot({ path: finalPng });
  console.log('[DEMO] Final screenshot:', finalPng);

  await browser.close();
  if (obsWs) try { obsWs.close(); } catch {}

  console.log('\n════════════════════════════════════════');
  console.log('  DEMO SESSION COMPLETE');
  console.log('════════════════════════════════════════');
  if (!noObs) console.log('  Recording:', recordingPath);
  console.log('  Transcript:', TRANSCRIPT);
  console.log('  Preflight:', preflightPng);
  console.log('  Confirm:', confirmPng);
  console.log('  Final:', finalPng);
}

main().catch(err => {
  console.error('\n[DEMO] Fatal error:', err.message);
  if (obsWs) try { obsWs.close(); } catch {}
  process.exit(1);
});
