// LessonSliceData.ts — AUTO-GENERATED by scripts/build-lesson-slices.js
// Do not edit by hand. Re-run the build script to regenerate.

export type LessonCaption = {
  startS: number;
  endS: number;
  text: string;
};

// ── Slice 1 ─────────────────────────────────────────────────────────────────
export const SLICE1_AUDIO = 'lesson1-slice01.mp3';
export const SLICE1_TOTAL_SEC = 89.68;
export const SLICE1_CAPTIONS: LessonCaption[] = [
  { startS: 0, endS: 1.73, text: "What you are about to see is" },
  { startS: 1.73, endS: 4.36, text: "something most men spend their entire lives" },
  { startS: 4.36, endS: 7.22, text: "never figuring out. They see a woman like this." },
  { startS: 7.22, endS: 10.68, text: "They feel that pull. And they do nothing. They walk past." },
  { startS: 10.68, endS: 14.5, text: "They go home. They tell themselves next time will be different." },
  { startS: 14.5, endS: 17.24, text: "And next time — they do the exact same thing." },
  { startS: 17.24, endS: 19.75, text: "Here is what those men do not understand." },
  { startS: 19.75, endS: 23.39, text: "The problem is never confidence. The problem is never looks." },
  { startS: 23.39, endS: 25.42, text: "The problem is never what to say." },
  { startS: 25.42, endS: 27.74, text: "The problem is that nobody ever showed" },
  { startS: 27.74, endS: 29.53, text: "them how this actually works." },
  { startS: 29.53, endS: 31.32, text: "Today I am going to show you." },
  { startS: 31.32, endS: 33.11, text: "You are going to watch a real" },
  { startS: 33.11, endS: 35.98, text: "approach from start to finish. How to stop her." },
  { startS: 35.98, endS: 37.29, text: "How to make her stay." },
  { startS: 37.29, endS: 39.26, text: "How to build something real in a" },
  { startS: 39.26, endS: 41.89, text: "matter of minutes with a complete stranger." },
  { startS: 41.89, endS: 43.62, text: "And I am going to stop along" },
  { startS: 43.62, endS: 45.64, text: "the way and show you exactly what" },
  { startS: 45.64, endS: 47.73, text: "is happening beneath the surface —" },
  { startS: 47.73, endS: 49.88, text: "because what you see on the outside" },
  { startS: 49.88, endS: 52.33, text: "and what is actually going on underneath" },
  { startS: 52.33, endS: 54.53, text: "are two completely different things." },
  { startS: 54.53, endS: 56.32, text: "By the time this lesson ends," },
  { startS: 56.32, endS: 58.35, text: "you will have a set of principles" },
  { startS: 58.35, endS: 61.75, text: "you can use anywhere. Not tricks. Not lines. Principles." },
  { startS: 61.75, endS: 64.14, text: "Things that work because they are based" },
  { startS: 64.14, endS: 66.47, text: "on how attraction actually functions —" },
  { startS: 66.47, endS: 68.32, text: "not on what society tells you," },
  { startS: 68.32, endS: 71.3, text: "not on what movies show you, but on what is real." },
  { startS: 71.3, endS: 74.46, text: "There is one rule before we begin. Watch everything." },
  { startS: 74.46, endS: 76.97, text: "Not just what I say — watch how I say it." },
  { startS: 76.97, endS: 79.53, text: "Watch the timing. Watch what I do not say." },
  { startS: 79.53, endS: 82.22, text: "Because sometimes the most important move is" },
  { startS: 82.22, endS: 84.9, text: "the one you cannot hear. She is right there." },
  { startS: 84.9, endS: 85.74, text: "Let us begin." },
];

// ── Slice 2 ─────────────────────────────────────────────────────────────────
export const SLICE2_AUDIO = 'lesson1-slice02.mp3';
export const SLICE2_TOTAL_SEC = 81.61;
export const SLICE2_CAPTIONS: LessonCaption[] = [
  { startS: 0, endS: 2.34, text: "Before I take a single step toward her," },
  { startS: 2.34, endS: 3.98, text: "I want you to notice what I" },
  { startS: 3.98, endS: 4.8, text: "am not doing." },
  { startS: 4.8, endS: 7.08, text: "I am not rehearsing a line in my head." },
  { startS: 7.08, endS: 9.49, text: "I am not waiting for the perfect moment." },
  { startS: 9.49, endS: 11.53, text: "I am not asking myself whether she" },
  { startS: 11.53, endS: 13.23, text: "will like me or whether I am" },
  { startS: 13.23, endS: 14.93, text: "good enough. I am observing." },
  { startS: 14.93, endS: 18.15, text: "This is the first thing most men get completely wrong." },
  { startS: 18.15, endS: 21.61, text: "They spend so much time inside their own heads — planning," },
  { startS: 21.61, endS: 24.94, text: "calculating, worrying — that by the time they are ready," },
  { startS: 24.94, endS: 27.99, text: "the moment is gone. And they use that as an excuse." },
  { startS: 27.99, endS: 29.63, text: "They say the moment passed." },
  { startS: 29.63, endS: 31.97, text: "The truth is they killed it themselves." },
  { startS: 31.97, endS: 33.9, text: "There is something I want you to" },
  { startS: 33.9, endS: 36.01, text: "remember for the rest of your life." },
  { startS: 36.01, endS: 38.06, text: "The woman standing in front of you" },
  { startS: 38.06, endS: 41.1, text: "is not thinking about you. She is in her own world." },
  { startS: 41.1, endS: 43.04, text: "She does not know you exist yet." },
  { startS: 43.04, endS: 45.79, text: "That means you have something most men waste —" },
  { startS: 45.79, endS: 48.95, text: "a blank slate. No judgment. No expectations. Nothing." },
  { startS: 48.95, endS: 52.81, text: "What you do in the next thirty seconds will determine everything." },
  { startS: 52.81, endS: 54.86, text: "I am going to walk over there now." },
  { startS: 54.86, endS: 57.26, text: "Watch what I say — and more importantly," },
  { startS: 57.26, endS: 58.73, text: "watch what I do not say." },
  { startS: 58.67, endS: 60.27, text: "Hey — sorry to interrupt." },
  { startS: 60.27, endS: 62.99, text: "Can I tell you something for just a second?" },
  { startS: 62.99, endS: 65.33, text: "I was walking past and I had to stop." },
  { startS: 65.33, endS: 69.28, text: "You have this energy — like you belong somewhere else entirely." },
  { startS: 69.28, endS: 72.18, text: "Not here. Somewhere quieter. More interesting." },
  { startS: 72.18, endS: 75.08, text: "I don't know why but that caught my attention." },
  { startS: 75.08, endS: 77.67, text: "Strange things are usually the most true." },
];

// ── Slice 3 ─────────────────────────────────────────────────────────────────
export const SLICE3_AUDIO = 'lesson1-slice03.mp3';
export const SLICE3_TOTAL_SEC = 98.9;
export const SLICE3_CAPTIONS: LessonCaption[] = [
  { startS: 0, endS: 3.02, text: "Stop. Right there. Did you notice what just happened?" },
  { startS: 3.02, endS: 5.15, text: "I did not tell her she was beautiful." },
  { startS: 5.15, endS: 7.44, text: "I did not tell her she had a nice smile." },
  { startS: 7.44, endS: 8.84, text: "I did not say any of the" },
  { startS: 8.84, endS: 10.85, text: "things that every other man who has" },
  { startS: 10.85, endS: 14.27, text: "ever approached her has said. I made a specific observation." },
  { startS: 14.27, endS: 15.16, text: "Something real." },
  { startS: 15.16, endS: 18.69, text: "Something that showed I was actually paying attention to her —" },
  { startS: 18.69, endS: 20.2, text: "not just to how she looks," },
  { startS: 20.2, endS: 21.65, text: "but to who she is in that" },
  { startS: 21.65, endS: 22.1, text: "moment." },
  { startS: 22.1, endS: 24.06, text: "Here is why this matters more than" },
  { startS: 24.06, endS: 26.07, text: "anything else you will learn today." },
  { startS: 26.07, endS: 28.42, text: "When you compliment a woman's appearance," },
  { startS: 28.42, endS: 31.05, text: "her radar receives that signal and immediately" },
  { startS: 31.05, endS: 32.5, text: "files it into a category." },
  { startS: 32.5, endS: 34.46, text: "She has heard it a thousand times." },
  { startS: 34.46, endS: 37.76, text: "She knows exactly what it means and exactly what you want." },
  { startS: 37.76, endS: 40.62, text: "The conversation is already over before it begins." },
  { startS: 40.62, endS: 42.74, text: "But when you say something specific —" },
  { startS: 42.74, endS: 45.2, text: "something that could only come from someone" },
  { startS: 45.2, endS: 48.9, text: "who was genuinely paying attention — something different happens." },
  { startS: 48.9, endS: 51.86, text: "She thinks: who is this person? How did he see that?" },
  { startS: 51.86, endS: 54.77, text: "That curiosity is the door opening. This is Step 1." },
  { startS: 54.77, endS: 58.01, text: "The observation opener. Not a compliment. An observation." },
  { startS: 58.01, endS: 60.42, text: "The difference between those two things is" },
  { startS: 60.42, endS: 62.71, text: "the difference between a man she forgets" },
  { startS: 62.71, endS: 64.34, text: "in ten seconds and a man she" },
  { startS: 64.34, endS: 67.75, text: "thinks about later. Find something real. Something specific." },
  { startS: 67.75, endS: 71.05, text: "Something only someone who was truly present would notice." },
  { startS: 71.05, endS: 73.74, text: "And say it without apology, without hesitation," },
  { startS: 73.74, endS: 77.04, text: "without needing her to validate it. That is how you begin." },
  { startS: 76.98, endS: 80.12, text: "You have been sitting here a while. Writing something?" },
  { startS: 80.12, endS: 82.29, text: "People who say they are just thinking" },
  { startS: 82.29, endS: 85.2, text: "are always thinking about something very specific." },
  { startS: 85.2, endS: 87.37, text: "You don't give much away, do you. No." },
  { startS: 87.37, endS: 89.19, text: "Actually — that is interesting." },
  { startS: 89.19, endS: 92.73, text: "Most people give everything away in the first thirty seconds." },
  { startS: 92.73, endS: 94.96, text: "You didn't. It is a problem sometimes." },
];
